# Generated by Django 4.1.7 on 2023-04-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
